package com.attendance.enums;

/** Audit action types for tracking all system events. */
public enum AuditAction {
    // Auth
    LOGIN, LOGOUT, LOGIN_FAILED, PASSWORD_CHANGED, PASSWORD_RESET,
    TOKEN_REFRESH,
    // Student
    STUDENT_CREATED, STUDENT_UPDATED, STUDENT_DELETED, STUDENT_IMPORTED,
    // Faculty / Admin
    FACULTY_CREATED, FACULTY_UPDATED, FACULTY_DELETED,
    // Department
    DEPARTMENT_CREATED, DEPARTMENT_UPDATED, DEPARTMENT_DELETED,
    // Subject
    SUBJECT_CREATED, SUBJECT_UPDATED, SUBJECT_DELETED,
    // Session
    SESSION_CREATED, SESSION_CLOSED, SESSION_PAUSED, SESSION_RESUMED,
    // QR
    QR_GENERATED, QR_SCANNED, QR_EXPIRED, QR_INVALID,
    // Attendance
    ATTENDANCE_MARKED, ATTENDANCE_UPDATED,
    // Network
    NETWORK_ALLOWED, NETWORK_BLOCKED,
    // Report
    REPORT_GENERATED, REPORT_EXPORTED,
    // System
    ADMIN_ACTION, SYSTEM_ERROR
}
